yarnPath: ".yarn/releases/yarn-berry.cjs"
# needed to get Veramo libs to work with yarn3 + pnp:
pnpMode: loose
# might have to fall back to this if we have deeper dependency probz:
#nodeLinker: node-modules